# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = "2026.7.5"

[settings]
experimental = true

[tools]
"aqua:taiki-e/cargo-llvm-cov" = "0.8.7"
gh = "2.96.0"
jq = "1.8.2"
rust = { version = "1.97.1", profile = "minimal", components = [
  "clippy",
  "llvm-tools-preview",
  "rustfmt",
] }

[bootstrap.packages]
# APT
"apt:apt-utils" = "latest"
"apt:build-essential" = "latest"
"apt:debsigs" = "latest"
"apt:createrepo-c" = "latest"
"apt:gnupg" = "latest"
"apt:libssl-dev" = "latest"
"apt:pkg-config" = "latest"
"apt:rpm" = "latest"

# DNF
"dnf:createrepo_c" = "latest"
"dnf:gcc" = "latest"
"dnf:gnupg2" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:pkgconf-pkg-config" = "latest"
"dnf:rpm" = "latest"

[task_config]
dir = "{{cwd}}"
includes = [
  "git::https://github.com/dimidiumlabs/infra.git//tasks?ref=8bc35fe8be889c50db2d1fb4425cc1b4097dc6b8",
]
