# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = "2026.7.5"

[settings]
experimental = true

[task_config]
dir = "{{cwd}}"
includes = [
  "git::https://github.com/dimidiumlabs/infra.git//tasks?ref=f2506479af3e8eac34b675582878ac783a5effda",
]
